### ISSUE TITLE
username-checker / instagram checker not working 

### ISSUE THREAD

**Issue by murattitone** [mov-ebx/username-checker#1]
I installed ur requirements and execute main.py then run checker 4, but nothing happened after that. Could you please check it, thank you.

**Comment by murattitone** [comment]
just saying "Running Instagram..." then nothing happening

**Comment by mov-ebx** [comment]
It is running, however, the current version that you were using lacked multi-threading, so it was probably so slow that going through one of the built-in presets would take hours.
It was working at the time, just that old version was slow,

**Comment by deepseeko** [comment]
thx man
