### ISSUE TITLE
Very slow.

### ISSUE THREAD

**Issue by joblessxd** [mov-ebx/username-checker#6]
The generator is very slow its been 5 mins and still nothing? When i try using the proxies it says "Error object of type '_io.TextIOWrapper' has no len()"
![image](https://github.com/mov-ebx/username-checker/assets/125808130/72086927-d01e-4608-ae34-09a7494a1810)
![image](https://github.com/mov-ebx/username-checker/assets/125808130/ac9b208c-6976-4057-8326-fa3eab3ea30c)

PLS help.

**Comment by mov-ebx** [comment]
the words.txt file has 13044 lines and you're only using 10 threads. no wonder its slow 😂
+ if you're not using proxies you have to wait rate-limit times
